baseurl: "https://iros2022-pnarude.github.io/"
title: "PNARUDE"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "PNARUDE Workshop"
  ShortName: "PNARUDE @ IROS'22"
  Description: "Perception and Navigation for Autonomous Robotics in Unstructured and Dynamic Environments"
  Date: "October 27th"
  # Price: "Only $100" # If your event is free, just comment this line
  Location: "Room C-2 @ ICC Kyoto"
  Venue: ""
  Address: ""
  City:  "Kyoto"
  State: "Japan"
  Images: ["/img/badge.png"]
  # GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
#    - dates
    - speakers
    - schedule
    - papers
    - organizers
#    - submission

  # Titles which you can translate to other languages
  Titles:
    about: "Overview"
#    dates: "Important Dates"
    speakers: "Speakers"
    schedule: "Schedule"
    papers: "Accepted Papers"
    organizers: "Organizers"
#    submission: "Submission"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  # CallToAction:
  #   text: "Register now!"
  #   link: "http://register.example.com"

  # List of Sponsors
  Speakers:
    - name: "Hugo"
      logo: "/img/hugo.png"
      url: "http://gohugo.io"

  # The entire schedule
  Schedule:
    - name: "Opening Remarks by the PNARUDE Organizers"
      time: "9:00"

    - name: "Perception and Sensor Fusion"
      headline: "Topic 1"
      time: "9:10"

    - name: "Prof. Cyrill Stachniss"
      photo: "/img/stachniss.jpg"
      bio: "Cyrill Stachniss is a German roboticist. He is a Full Professor at the University of Bonn and heads the lab for Photogrammetry and Robotics. He is additionally a Visiting Professor in Engineering at the University of Oxford. He made significant contributions to problem of the mobile robot exploration, simultaneous localization and mapping (SLAM) as well as other topics related to mobile robotics."
      company: "University of Bonn, Germany"
      link:
        href: ""
        text: ""
      presentation:
        title: "Perception for Robots in the Fields"
        description: "TODO Talk Description"
        time: ""

    - name: "Prof. Yusuke Tamura"
      photo: "/img/tamura.png"
      bio: "Yusuke Tamura is currently an Associate Professor with the Department of Robotics, Graduate School of Engineering, Tohoku University, Sendai, Japan. His research interests include human–robot interaction, mobile robotics, and remote control technology."
      company: "Tohoku University, Japan"
      presentation:
        title: "Towards safe and smooth Coexistence of mobile Robots and inattentive Humans"
        description: "TODO Talk Description"
        time: ""

    - name: "Coffee Break"
      time: "10:10"

    - name: "Navigation and Mobility"
      headline: "Topic 2"
      time: ""

    - name: "Dr. Marija Popović"
      photo: "/img/popovic.jpg"
      bio: 'Marija Popović is a Junior Research Group Leader at the University of Bonn and Cluster of Excellence "PhenoRob". Her research is centred around developing algorithms to enable intelligent decision-making for autonomous mobile robots, both aerial and ground. Her research group in PhenoRob focuses on furthering robot autonomy in agricultural applications.'
      company: "University of Bonn, Germany"
      link:
        href: ""
        text: ""
      presentation:
        title: "Mapping and Planning for Autonomous Robotic Decision-Making"
        description: "TODO Talk Description"
        time: "10:20"

    - name: "Ruben Mascaro Palliser"
      photo: "/img/palliser.jpg"
      bio: "Ruben started his PhD at the Vision for Robotics Lab, lead by Margarita Chli, in October 2018. He has previously worked as a software engineer in the automotive industry and as a research assistant at the Automatic Control Department (ESAII) of the Polytechnic University of Catalonia. His main interests are vision-based localization, mapping and higher-level scene understanding algorithms for autonomous robots."
      company: "ETH Zurich, Switzerland"
      link:
        href: ""
        text: ""
      presentation:
        title: "Semantic Scene Understanding for Robotic Navigation and Mobility in Unstructured Environments"
        description: "TODO Talk Description"
        time: "10:50"

    - name: "Oral Spotlight Presentations #1"
      presentation:
        title: "test"
        time: "11:20"
      spotlight:
        titles: 
          -
            authors: "Hyesu Jang, Minwoo Jung, Sangwoo Jung and Ayoung Kim"
            presenter: "Hyesu Jang" 
            title: "Radar-based Angular Correction for Tightly-coupled LiDAR Odometry"
            url: "pdf/PNARUDE_IROS2022_Hyesu_Jang_Radar-based_Angular_Correction_for_TIghtly-coupled_LiDAR_Odometry.pdf"
            video: 
          - 
            authors: "Felicia Ruppel, Florian Faion, Claudius Gläser and Klaus Dietmayer"
            presenter: "Felicia Ruppel"
            title: "Can Transformer Attention Spread Give Insights Into Uncertainty of and Tracked Objects?"
            url: "pdf/PNARUDE_IROS2022_Felicia_Ruppel_Can_Transformer_Attention_Spread_Give_Insights_Into_Uncertainty_of_Detected_and_Tracked_Objects.pdf"
            video:
          -
            authors: "Diego Martı́nez, Luis Riazuelo and Luis Montano"
            presenter: "Diego Martı́nez"
            title: "Deep Reinforcement Learning oriented for Real World Dynamic Scenario"
            url: "pdf/PNARUDE_IROS2022_Diego_Martinez_Baselga_Deep_Reinforcement_Learning_oriented_for_Real_World_Dynamic_Scenario.pdf"
            video: 
          -
            authors: "Shutong Jin, Zhenyu Wu, Chunyang Zhao, Jun Zhang, Guohao Peng and Danwei Wang"
            presenter: "Zhenyu Wu"
            title: "SectionKey: 3-D Semantic Point Cloud Descriptor for Place Recognition"
            url: "pdf/PNARUDE_IROS2022_Shutong_Jin_Zhenyu_Wu_SectionKey_3-D_Semantic_Point_Cloud_Descriptor_for_Place_Recognition.pdf"
            video:
          -
            authors: "Riccardo Polvara, Sergi Molina Mellado, Ibrahim Hroob, Grzegorz Cielniak and Marc Hanheide"
            presenter: "Riccardo Polvara"
            title: "Collection and Evaluation of a Long-Term 4D Agri-Robotic Dataset"
            url: "pdf/PNARUDE_IROS2022_Riccardo_Polvara_Collection_and_Evaluation_of_a_Long-Term_4D_Agri-Robotic_Dataset.pdf"
            video:

    - name: "Lunch"
      time: "12:00"

    - name: "AI-based Autonomy"
      time: ""
      headline: "Topic 3"

    - name: "Prof. Huijing Zhao"
      photo: "/img/zhao.jpg"
      bio: "Huijing Zhao is a Professor of Machine Intelligence at Peking University. Her research interest covers image sensing, computer vision, and spatial data handling for GIS applications."
      company: "Peking University, China"
      link:
        href: ""
        text: ""
      presentation:
        title: "Understanding the Challenges When 3D Semantic Segmentation Faces Class Imbalanced and OOD Data"
        description: "TODO Talk Description"
        time: "13:00"

    - name: "Prof. François Pomerleau"
      photo: "/img/pomerleau.jpg"
      bio: "François Pomerleau is a professor in the Computer Science and Software Engineering Department at Laval University in Canada. His research interests include 3D reconstruction of environments using laser data, autonomous navigation, search and rescue activities, environmental monitoring, trajectory planning and scientific methodology applied to robotics."
      company: "Laval University, Canada"
      link:
        href: ""
        text: ""
      presentation:
        title: "From subarctic to subterranean environments: how to localize in unstructured environments?"
        description: "TODO Talk Description"
        time: "13:30"

    - name: "Coffee Break"
      time: "14:00"

    - name: "Applications of AI"
      headline: "Topic 4"
      time: ""

    - name: "Dr. Roland Lenain"
      photo: "/img/lenain.jpg"
      bio: "Dr. Roland Lenain is a researcher in off-road mobile robotics at the TSCF unit of INRAE at Clermont-Ferrand. Roland is also in charge of the RobAgri association and his research interests include adaptive and predictive control of mobile robots in the context of natural environment and its application in the field of agricultural robotics."
      company: "INRAE, France"
      link:
        href: ""
        text: ""
      presentation:
        title: "Robotics in Agriculture: Toward the adaption of Robot(s) Behaviors to meet new Agroecological Expectation"
        description: "TODO Talk Description"
        time: "14:10"

    - name: "Prof. Danwei Wang"
      photo: "/img/wang.jpg"
      bio: "Danwei Wang is professor in the School of Electrical and Electronic Engineering at NTU and director at the ST Engineering-NTU Corporate Lab. His research interests include robot active perception and multi-modal sensor fusion, robot autonomy and traffic signal control for urban road networks."
      company: "Nanyang Technological University, Singapore"
      link:
        href: ""
        text: ""
      presentation:
        title: "Multi-modal Perception in adverse Weather Conditions"
        description: "TODO Talk Description"
        time: "14:40"

    - name: "Coffee Break"
      time: "15:10"

    - name: "Oral Spotlight Presentations #2"
      presentation:
        title: "test"
        time: "15:20"
      spotlight:
        titles: 
          -
            authors: "Francesco Verdoja, Tomasz Piotr Kucner, Ville Kyrki"
            presenter: "Verdoja Francesco"
            title: "Generating people flow from architecture of real unseen environments"
            url: "pdf/PNARUDE_IROS2022_Francesco_Verdoja_Generating_people_flow_from_architecture_of_real_unseen_environments.pdf"
            video:
          -
            authors: "Carmelo Scribano, Giorgia Franchini, Ignacio Sañudo Olmedo and Marko Bertogna"
            presenter: "Carmelo Scribano"
            title: "CERBERUS: Simple and Effective All-In-One Automotive Perception Model with Multi Task Learning"
            url: "pdf/PNARUDE_IROS2022_Carmelo_Scribano_CERBERUS_Simple_and_Effective_All_In_One_Automotive_Perception_Model_with_Multi_Task_Learning.pdf"
            video: 
          -
            authors: "Yinan Deng, Meiling Wang, Danwei Wang and Yufeng Yue"
            presenter: "Yinan Deng"
            title: "S-MKI: Incremental Dense Semantic Occupancy Reconstruction Through Multi-Entropy Kernel Inference"
            url: "pdf/PNARUDE_IROS2022_Yinan_Deng_S-MKI_Incremental_Dense_Semantic_Occupancy_Reconstruction_Through_Multi-Entropy_Kernel_Inference.pdf"
            video: "video/PNARUDE_IROS2022_Video-Presentation_Yinan_Deng_S-MKI_Incremental_Dense_Semantic_Occupancy_Reconstruction_Through_Multi-Entropy_Kernel_Inference.mp4"
          -
            authors: "César Debeunne, Alex Torres and Damien Vivet"
            presenter: "César Debeunne"
            title: "Design of a bi-monocular Visual Odometry System for Lava Tubes exploration"
            url: "pdf/PNARUDE_IROS2022_Cesar_Debeunne_Design_of_a_bi-monocular_Visual_Odometry_System_for_Lava_Tubes_exploration.pdf"
            video: "video/PNARUDE_IROS2022_Video-Presentation_Cesar_Debeunne_Design_of_a_bi-monocular_Visual_Odometry_System_for_Lava_Tubes_exploration.mp4"
          - 
            authors: "Yash Goel, Narunas Vaskevicius, Luigi Palmieri, Nived Chebrolu, Cyrill Stachniss"
            presenter: "Yash Goel"
            title: "Predicting Dense and Context-aware Cost Maps for Semantic Robot Navigation"
            url: "pdf/PNARUDE_IROS2022_Yash_Goel_Narunas_Vaskevicius_Predicting_Dense_and_Context-aware_Cost_Maps_for_Semantic_Robot_Navigation.pdf"
            video: 

    - name: "Roundtable Discussion: Future Advances and Research Directions"
      time: "15:50"

    - name: "Closing Remarks"
      time: "16:10"

  Organizers:
    - name: "Prof. Danwei Wang"
      photo: "/img/wang.jpg"
      university: "Nanyang Technological University, Singapore"
      url: "https://personal.ntu.edu.sg/edwwang/"
      email: "edwwang@ntu.edu.sg"
      type: "main"

    - name: "Prof. Yufeng Yue"
      photo: "/img/yue.jpg"
      university: "Beijing Institute of Technology"
      url: "https://www.researchgate.net/profile/Yufeng-Yue"
      email: "yueyufeng@bit.edu.cn"
      type: "co"

    - name: "Dr. Philippe Martinet"
      photo: "/img/martinet.jpg"
      university: "INRIA Sophia-Antipolis"
      url: "https://project.inria.fr/chorale/members/philippe-martinet/"
      email: "philippe.martinet@inria.fr"
      type: "co"

    - name: "Dr. Christian Laugier"
      photo: "/img/laugier.jpg"
      university: "INRIA Grenoble Rhône-Alpes"
      url: "https://scholar.google.com/citations?user=jtnM0c8AAAAJ&hl=en"
      email: "christian.laugier@inria.fr"
      type: "co"

    - name: "Dr. Roland Lenain"
      photo: "/img/lenain.jpg"
      university: "INRAE Paris"
      url: "https://www6.clermont.inrae.fr/tscf/Annuaire/Pages-chercheurs/Roland-Lenain"
      email: "roland.lenain@inrae.fr"
      type: "co"

    - name: "Prof. Abhinav Valada"
      photo: "/img/valada.jpg"
      university: "University of Freiburg"
      url: "https://rl.uni-freiburg.de/people/valada"
      email: "valada@cs.uni-freiburg.de"
      type: "co"

    - name: "Dr. Jens Behley"
      photo: "/img/behley.jpg"
      university: "University of Bonn"
      url: "https://www.ipb.uni-bonn.de/people/jens-behley/"
      email: "jens.behley@igg.uni-bonn.de"
      type: "co"

    - name: "Peter Mortimer"
      photo: "/img/mortimer.jpg"
      university: "Bundeswehr University of Munich"
      url: "https://www.unibw.de/tas-en/institute/team/peter-jan-mortimer"
      email: "peter.mortimer@unibw.de"
      type: "co"

    - name: "Raphael Hagmanns"
      photo: "/img/hagmanns.jpg"
      university: "Fraunhofer IOSB"
      url: "https://raphaelhagmanns.gitlab.io/"
      email: "raphael.hagmanns@iosb.fraunhofer.de"
      type: "co"

  Submission:
    topics:
      - name: "Perception and Navigation in Unstructured & Dynamic Environments"
      - name: "Mobility in Unstructured Environments"
      - name: "Detection, Tracking and Classification"
      - name: "Feature Extraction and Feature Selection"
      - name: "Collision Prediction and Avoidance"
      - name: "Path Planning and Re-Planning"
      - name: "Multi-Sensor Calibration and Fusion"
      - name: "SLAM in Unstructured Environments"
      - name: "Environmental Mapping and Reconstruction"
      - name: "Deep Learning Applied in Unstructured Environments"
      - name: "Deep Reinforcement Learning Applied in Unstructured Environments"
      - name: "Decision-making by taking into account Human-Robot Interactions"
